(* ::Package:: *)

BeginPackage["DirectDM`"]


Begin["`Private`"]


(* import the evolution matrices for double insertions, 
the matrix is generated by Umat_doubleinsert.m, which should be rerun if the inputs.m 
is modified
*)
UquarkDoubleInsert=Import[NotebookDirectory[]<>"Umat.dat"];
UleptonDoubleInsert=Import[NotebookDirectory[]<>"UmatLep.dat"];


(* 
the input are C6i at MZ
for quarks:
C6qinput={C61u, C62u, C63u, C64u,C61d, C62d, C63d, C64d, C61s, C62s, C63s, C64s, C61c, C62c, C63c, C64c, C61b, C62b, C63b, C64b}
for leptons:
C6linput={C61e, C62e, C63e, C64e,C61mu, C62mu, C63mu, C64mu,C61tau, C62tau, C63tau, C64tau}

the output are C8i at \[Mu]=2 GeV
{C81u, C82u, C83u, C84u,C81d, C82d, C83d, C84d, C81s, C82s, C83s, C84s} 
*)

C8fromC6DoubleInsert[C6qinput_,C6linput_]:=UquarkDoubleInsert.C6qinput+UleptonDoubleInsert.C6linput;


End[]


EndPackage[]
